### ISSUE TITLE
Add an Admin menu displaying who has prime status/recent VAC

### ISSUE THREAD

**Issue by rcon420** [azalty/sm-no-dupe-account#1]
Hey, maybe you could add an admin menu to display who has prime status and maybe recent vac status?

I know there is a plugin that gives nonprime players Tab tags but I don't want to bully them for having free to play version of CS:GO.

**Comment by azalty** [comment]
Good idea! Version 1.3.0 is already pretty much finished with:
- Logging cvar (logs check approvals/refusals)
- Steam Bans method (refuse player if VAC/Game/Community Banned or Recent VAC/Game ban, configurable)

Adding your suggestion will mean I'll have to change what I did, I'm thinking of adding the `!nda` command where every menu will be accessible

**Comment by azalty** [comment]
I think I have finished, now I have to translate everything to french and test the plugin

Adding the database is something I really want but it might be complicated for the future. I have to think of a way to make it compatible with future versions and also compatible if people want to switch to previous versions. I want to have a system that automatically updates the database, and safely remove old tables. Sadly with SQLite it's apparently not possible (but I know a little trick). I don't know a thing about MySQL, but I want support for SQLite mainly. This means I have to write 2 times each database query, and do 2 updating methods. It'll probably take some time and I prefer adding other features for now.

I want to do a powerful database that will work through updates, not one that breaks each update.

You probably don't care but I prefer talking rather than staying silent :)

**Comment by rcon420** [comment]
> I think I have finished, now I have to translate everything to french and test the plugin
> 
> Adding the database is something I really want but it might be complicated for the future. I have to think of a way to make it compatible with future versions and also compatible if people want to switch to previous versions. I want to have a system that automatically updates the database, and safely remove old tables. Sadly with SQLite it's apparently not possible (but I know a little trick). I don't know a thing about MySQL, but I want support for SQLite mainly. This means I have to write 2 times each database query, and do 2 updating methods. It'll probably take some time and I prefer adding other features for now.
> 
> I want to do a powerful database that will work through updates, not one that breaks each update.
> 
> You probably don't care but I prefer talking rather than staying silent :)

Don't worry I care  I follow your project for some time already :). I have made some suggestions on alliedmodders as well!

**Comment by azalty** [comment]
> Don't worry I care I follow your project for some time already :). I have made some suggestions on alliedmodders as well!

Thanks! :)

I prefer having them here since it is easier to track and discuss about it but I read both. I have a .txt file with some requests

The next requests I have are:
- Immunity for admins with a certain flag (or whitelist for certain flag/steamid)
- Store players in databases

**Comment by rcon420** [comment]
I have suggestion for !nda menu when you add the Prime Status section just list Players without Prime status I think it's obvious that everyone else has a Prime Status.

**Comment by azalty** [comment]
Oops, totally forgot to add the prime menu

Anyways I have more things to fix with this update it seems, why do I always find bug right after publishing a version :(

**Comment by crashzk** [comment]
I just wanted to say that the plugin is perfect, thanks.

Looking forward to the version with support for:

> * Immunity for admins with a certain flag (or whitelist for certain flag/steamid)
> * Store players in databases

**Comment by azalty** [comment]
> 
> 
> I just wanted to say that the plugin is perfect, thanks.
> 
> Looking forward to the version with support for:
> 
> > * Immunity for admins with a certain flag (or whitelist for certain flag/steamid)
> > * Store players in databases

These are already planned, but it's always good to have it here to remember me, could you please [create a new feature request](https://github.com/azalty/sm-no-dupe-account/issues/new/choose) with these infos?

**Comment by azalty** [comment]
Non-prime status menu added in 1.3.1 (https://github.com/azalty/sm-no-dupe-account/releases/tag/1.3.1)

Close this issue if you think I have added what you were asking for

**Comment by crashzk** [comment]
> > I just wanted to say that the plugin is perfect, thanks.
> > Looking forward to the version with support for:
> > > * Immunity for admins with a certain flag (or whitelist for certain flag/steamid)
> > > * Store players in databases
> 
> These are already planned, but it's always good to have it here to remember me, could you please [create a new feature request](https://github.com/azalty/sm-no-dupe-account/issues/new/choose) with these infos?

Do I believe this to be correct?

https://github.com/azalty/sm-no-dupe-account/issues/4
https://github.com/azalty/sm-no-dupe-account/issues/5

In any case it is only done for registration and to close when it is implemented.
