### ISSUE TITLE
Snice I updated plugin I don't see Prime Status Section

### ISSUE THREAD

**Issue by rcon420** [azalty/sm-no-dupe-account#14]
**Describe the bug**
A clear and concise description of what the bug is as well as how to reproduce it.
Since I updated the plugin I don't see Prime Status Section in the !NDA panel might be Translation or other issue havent ;looked into it.
**Error logs**
If any error log, paste it here or screenshot it.
no errors.

**Comment by azalty** [comment]
- Is Steamworks installed?
- What is the value of `nda_prime`?

**Comment by rcon420** [comment]
> * Is Steamworks installed?
> * What is the value of `nda_prime`?
yes

// (Requires SteamWorks)
// 0 = disabled
// 1 = is a user check that fails if user is not prime (will only work if user paid the game)
// -
// Default: "1"
nda_prime "0"

I disabled the check but I don't think the Prime status menu should be removed.

**Comment by azalty** [comment]
> > * Is Steamworks installed?
> 
> > * What is the value of `nda_prime`?
> 
> yes
> 
> 
> 
> // (Requires SteamWorks)
> 
> // 0 = disabled
> 
> // 1 = is a user check that fails if user is not prime (will only work if user paid the game)
> 
> // -
> 
> // Default: "1"
> 
> nda_prime "0"
> 
> 
> 
> I disabled the check but I don't think the Prime status menu should be removed.

The cvar changed but it seems your description wasn't updated correctly

You need to put `nda_prime "2"` to add the menu, else the script won't check wether players are prime or not

You can get a complete list of cvars and their updated description on the alliedmodders thread.

I'll try to see if it's possible to update the description as well in a future update.

**Comment by rcon420** [comment]
nda prime 2 works but for some reason it shows my own profile as non prime now before it didnt show me as non prime

**Comment by azalty** [comment]
> nda prime 2 works but for some reason it shows my own profile as non prime now before it didnt show me as non prime

This happens if you reloaded the plugin mid-game or you changed the cvar without disconnecting/reconnecting after. It says you are not prime since you didn't got checked

**Comment by rcon420** [comment]
> > nda prime 2 works but for some reason it shows my own profile as non prime now before it didnt show me as non prime
> 
> This happens if you reloaded the plugin mid-game or you changed the cvar without disconnecting/reconnecting after. It says you are not prime since you didn't got checked

yeah idk I get this all the time. I don't reload this plugin mid-game or change cvars.

**Comment by azalty** [comment]
Does every player appear as non prime or only some?

We are only able to detect paid primes (players who paid the game to become prime)

**Comment by rcon420** [comment]
> Does every player appear as non prime or only some?
> 
> We are only able to detect paid primes (players who paid the game to become prime)

whole server is non prime with CVAR nda prime 2
I bought cs:go at 2015 i show as non prime

**Comment by azalty** [comment]
It seems like a bug indeed

I'll take a look at it.

**Comment by rcon420** [comment]
> It seems like a bug indeed
> 
> I'll take a look at it.

Thank You maybe link me your Discord so we can get in touch in real-time? You are doing great work but sadly no one else is reporting issues. This plugin is def must need for skill shooting-based servers and much better than other similar releases.

**Comment by azalty** [comment]
> Thank You maybe link me your Discord so we can get in touch in real-time? You are doing great work but sadly no one else is reporting issues. This plugin is def must need for skill shooting-based servers and much better than other similar releases.

Thanks!

Here's my current discord tag: rlevet#9721

Here's my discord profile link in case I change username: https://discord.com/users/372454796805931019

EDIT: On my test server, nda_prime "2" is working fine and I'm not being detected as non-prime

**Comment by azalty** [comment]
This issue is probably related to an old one you had #15, please update to the main branch and test if it still does that :)

**Comment by azalty** [comment]
Fixed with #15, I contacted @rcon420 on discord.
