### ISSUE TITLE
Country Block filter

### ISSUE THREAD

**Issue by rcon420** [azalty/sm-no-dupe-account#18]
I think some server owners might be interested in such a filter where you can whitelist X countries or block x countries from connecting to the server. Thoughts?

**Comment by azalty** [comment]
Good idea :)

I might add this later

**Comment by azalty** [comment]
This is now available on the 1.5.0 Beta 1, located in the main branch.
This is a beta version, so it might have bugs. So far, everything seems working though.
Once it's tested a bit more, and I'm pretty confident no bugs are present, 1.5.0 will be released as a stable version.
It's up to you to see if you want to try the beta version :)

You might not even be using my plugin anymore, but 🤷

**Comment by azalty** [comment]
Added in the 1.5.0 stable release.
