### ISSUE TITLE
Kicking grounds too long, chat cuts the reason

### ISSUE THREAD

**Issue by crashzk** [azalty/sm-no-dupe-account#21]
## Describe the bug
Reasons for kicking too long, chat cuts the reason.

This happens for my language in the case Portuguese-BR, default language, English I have not verified.

I believe it must be because of the character limit of CSGO itself.

**Comment by azalty** [comment]
Is having the kick message in chat really that important? Mine are bugged, probably due to my chat processor

**Comment by crashzk** [comment]
In the chat I believe not, my doubt is if the reason appears completely for the player.

The information box that shows him when he is kicked, turns out to be all right.

**Comment by crashzk** [comment]
In any case, the PR #22 I made has simple changes to my language, I believe it solves the case of chat.
