### ISSUE TITLE
Steam Bans/Playtime request failed!

### ISSUE THREAD

**Issue by freakexeuLow** [azalty/sm-no-dupe-account#29]
**Describe the bug**
Unfortunately, I have these errors every day. Now I wanted to test the Master Brench and get there again other error messages. I give up slowly because it is currently the only plugin that reports these errors. The Prime status works so far, everything else again not

**Error logs**
1.4.4 **Stable**
```
L 04/27/2021 - 19:29:17: SourceMod error session started
L 11/11/2021 - 19:29:17: Info (map "de_dust2") (file "/home/user2-3/server/csgo/csgo/addons/sourcemod/logs/errors_20210427.log")
L 11/11/2021 - 19:29:17: [no_dupe_account.smx] Steam Bans request failed!
L 11/11/2021 - 19:29:18: [no_dupe_account.smx] Steam Bans request failed!
L 11/11/2021 - 19:29:19: [no_dupe_account.smx] Playtime request failed!
L 11/11/2021 - 19:55:49: Error log file session closed.
```

**Main**
```
L 11/11/2021 - 10:21:17: SourceMod error session started
L 11/11/2021 - 10:21:17: Info (map "de_mirage") (file "/home/user2-3/server/csgo/csgo/addons/sourcemod/logs/errors_20211111.log")
L 11/11/2021 - 10:21:17: [no_dupe_account.smx] Playtime request failed! - Status Code: 401
L 11/11/2021 - 10:21:17: [no_dupe_account.smx] Steam Age request failed! - Status Code: 403
L 11/11/2021 - 10:21:17: [no_dupe_account.smx] Steam Bans request failed! - Status Code: 403
L 11/11/2021 - 10:21:53: [no_dupe_account.smx] Playtime request failed! - Status Code: 401
L 11/11/2021 - 10:21:53: [no_dupe_account.smx] Steam Age request failed! - Status Code: 403
L 11/11/2021 - 10:21:53: [no_dupe_account.smx] Steam Bans request failed! - Status Code: 403
L 11/11/2021 - 10:23:43: [no_dupe_account.smx] Playtime request failed! - Status Code: 401
L 11/11/2021 - 10:23:43: [no_dupe_account.smx] Steam Bans request failed! - Status Code: 403
```

I will edit the post as far as I get new error messages, as I said I do not know any error of my side. I have even regenerated the cfg and API works also, have several other things running over it

**Comment by azalty** [comment]
401 = k_EHTTPStatusCode401Unauthorized
403 = k_EHTTPStatusCode403Forbidden

Notes: `You probably want 403 or something else. 401 implies you're sending a WWW-Authenticate header and the client can sent an Authorization header in response.` ([Source](https://partner.steamgames.com/doc/api/ISteamHTTP))

Are you sure you set the correct Steam API key in `nda_steamapi_key`? Verify it please (but don't share it here, it is meant to be kept private).

**Comment by azalty** [comment]
I added an error message to indicate that the Steam API Key that is set is incorrect in 1.5.0 Beta 5

**Comment by freakexeuLow** [comment]
i have already written it azalty privately, unfortunately yesterday the night was too long after all and had forgotten 1 number/letter in the API and currently it runs now without problems and already testing the 1.5.x version. If you want, you can close the topic or wait another 1,2 or 3 days if the 1.5.x reports problems azalty :)

**Comment by azalty** [comment]
Closing this issue because it was invalid.

If you have any problem, please comment on these issues #12 #28 or create a new one if the problem you're reporting isn't yet reported
