### ISSUE TITLE
Request failed! - Status Code: 0

### ISSUE THREAD

**Issue by crashzk** [azalty/sm-no-dupe-account#31]
### Describe the bug
Today I started getting the **`Status Code: 0`** error again.

Plugin version would be:
```
  28 "No Dupe Account" (1.5.0) by azalty
```
### Error logs
![image](https://user-images.githubusercontent.com/32937653/144528164-76bb98e6-3819-4410-af95-fe479bb38c7d.png)

[errors_20211202.log](https://github.com/azalty/sm-no-dupe-account/files/7646086/errors_20211202.log)

I can't say if it had to do with today's Steam problem.

https://steamstat.us/

![image](https://user-images.githubusercontent.com/32937653/144528324-c2a06337-22d5-439b-89e9-05fad9e6c363.png)

Previous days have some errors too, but much less, much less log compared to today's log.

**Comment by azalty** [comment]
`L 12/02/2021 - 20:24:40: [no_dupe_account.smx] Steam Bans request failed: CommunityBanned field is missing (potential Steam maintenance)! - Status Code: 200`

This thing again! #28 did occur another time here, and it indeed seemed like a maintenance yesterday. I'm curious though, I should've written what the API sent back, but as long as this problem is handled, it's fine.

For all the other fails, I'm really unsure, that's surely a lot of fails, but seems like retrying didn't change a thing. Perhaps the API failing was the reason behind yesterday's maintenance? (Assuming it was a planned maintenance)

Gotta love that Status code 0 basically gives us no infos :(

I really can't make a guess, let's just say it's Steam fault...

I would really like to get an explanation though, I'm pretty confident that the Steam API shouldn't fail that much, so I can't cease to think that it might be my fault, or that I can improve Steam requests/all requests in any way.

Do you use the Check IP feature? If yes, and it didn't fail, it probably mean it was the steam API's fault.

On my side, I didn't get a lot of 4/4 fails, but I got some for steam requests.

**Comment by azalty** [comment]
I think we can safely say it's Steam's fault if we don't have as many errors in the future.

Did you get any 4/4 fails in the previous days? Those should be a lot less frequent than 1/4 fails if my retry system works.

Thanks for letting me know about these fails!

**Comment by crashzk** [comment]
> I think we can safely say it's Steam's fault if we don't have as many errors in the future.
> 
> Did you get any 4/4 fails in the previous days? Those should be a lot less frequent than 1/4 fails if my retry system works.
> 
> Thanks for letting me know about these fails!

No, just yesterday you registered several, logs from previous days have some days that do not have and others that occur only once.

I believe it was due to this _"steam maintenance"_ itself.

In any case, I'll keep an eye on it from today until the weekend, I get all the error logs and send them here just so we can see if it happens again and several times.

**Comment by crashzk** [comment]
I got the most recent logs, 3 days, problem reoccurred in 2 days while in one day nothing was recorded.

Interesting that whenever Steam recorded error logs it recorded a drop even hours later.

https://steamstat.us/

[errors_20211203.log](https://github.com/azalty/sm-no-dupe-account/files/7656656/errors_20211203.log)
[errors_20211204.log](https://github.com/azalty/sm-no-dupe-account/files/7656654/errors_20211204.log)
[errors_20211205.log](https://github.com/azalty/sm-no-dupe-account/files/7656655/errors_20211205.log)

**Comment by crashzk** [comment]
It happened again almost now, and again steam had a connection problem apparently.

![image](https://user-images.githubusercontent.com/32937653/144760776-eedfefa5-030c-487d-8faf-6abd59cf6e9c.png)

![image](https://user-images.githubusercontent.com/32937653/144754124-c4742b8d-301a-454c-9d4d-3d2e77e5f821.png)

I'm starting to believe it's steam even correct? Or am I totally wrong?

**Comment by azalty** [comment]
@crashzk please hide the player IP or I'll have to remove your message

**Comment by azalty** [comment]
On your last screenshot, it worked, because as you can see, you didn't get a 4/4 fail.

No idea if it's because of Steam or my fault. I thought doing multiple tries would help for every reason, but I'm running out of ideas.

**Comment by azalty** [comment]
Try increasing `nda_http_request_timeout_delay` to `10` to see if it helps.

Location: `cfg/sourcemod/no_dupe_account_advanced.cfg`

However, the fact that only Steam requests seem to fail is pretty weird.

**Comment by crashzk** [comment]
> @crashzk please hide the player IP or I'll have to remove your message

I didn't find IP of players, just STEAM_ID. In any case I removed everything and left only the No Dupe Account logs.

**[EDIT]**
Sorry, I saw it in the image, I updated it.

**Comment by crashzk** [comment]
> On your last screenshot, it worked, because as you can see, you didn't get a 4/4 fail.
> 
> No idea if it's because of Steam or my fault. I thought doing multiple tries would help for every reason, but I'm running out of ideas.

Yes, I noticed too. But I forgot to warn you, during these logs/errors I noticed that players that didn't have the requirements were able to connect.

Anyway, I'm going to test, make the change you said and test it.

> Try increasing `nda_http_request_timeout_delay` to `10` to see if it helps.
> 
> Location: `cfg/sourcemod/no_dupe_account_advanced.cfg`
> 
> However, the fact that only Steam requests seem to fail is pretty weird.

**Comment by azalty** [comment]
> Yes, I noticed too. But I forgot to warn you, during these logs/errors I noticed that players that didn't have the requirements were able to connect.
 
When any request fail for a player, the player is automatically granted access to the server. This is done on purpose to prevent players from being falsely kicked.

**Comment by crashzk** [comment]
> > Yes, I noticed too. But I forgot to warn you, during these logs/errors I noticed that players that didn't have the requirements were able to connect.
> 
> When any request fail for a player, the player is automatically granted access to the server. This is done on purpose to prevent players from being falsely kicked.

Ok, but even with these failures the plugin tries to make the request again and if everything goes well it checks the player, if it doesn't have requirements is it kicked?

Or if he connected even without having the requirements once connected to the server the plugin won't kick until change map and do another check?

**Comment by azalty** [comment]
> Ok, but even with these failures the plugin tries to make the request again and if everything goes well it checks the player, if it doesn't have requirements is it kicked?
> 
> Or if he connected even without having the requirements once connected to the server the plugin won't kick until change map and do another check?

If any request fails, it will count as a passed "check". However, it won't bypass "requirements/kick methods". [(click here to remember what are checks)](https://github.com/azalty/sm-no-dupe-account/wiki/FAQ#whats-a-check)

**Comment by crashzk** [comment]
Oops, sorry for the delay **@azalty.**

So let's go, I'm using the latest version and I believe this problem has been solved, it even showed some logs, but they all solved it with just an attempt to make the request again.

![image](https://user-images.githubusercontent.com/32937653/151709507-416e4765-45cc-4ee6-a809-db3391cf6cef.png)

![image](https://user-images.githubusercontent.com/32937653/151709535-76f47e87-5e56-4f7b-9509-dfc81f89f10d.png)

I believe this issues can be marked as resolved.

**Comment by azalty** [comment]
As long as complete request fails (4/4) are rare enough, they can indeed be neglected.
