### ISSUE TITLE
Doubt with no_dupe_account.cfg file

### ISSUE THREAD

**Issue by crashzk** [azalty/sm-no-dupe-account#33]
I have a question with the **`no_dupe_account.cfg`** file:
```
"no_dupe_account"
{
	"Players" // Players whitelist
	{
		// Format:
		// "SteamID2 (starting with STEAM_1)"	"methods to disable, separated by ';'"
		// "IP"		"methods to disable, separated by ';'"
		// "flag"	"methods to disable, separated by ';'"
		// "$country code"	"methods to disable, separated by ';'"
		//
		// List of methods: (you can select them all with 'all')
		// Other: vpn, country (check below)
		// CSGO: csgo_level, csgo_playtime, prime, csgo_playtime, csgo_coin
		// Steam: steam_level, steam_age, bans_vac, bans_game, bans_community, bans_total, bans_recent
		// 
		// Examples:
		// "STEAM_1:0:11101"	"vpn;csgo_playtime;bans_vac;bans_game;bans_total" // prevents this user from being checked/verified by these methods
		// "STEAM_1:0:11101"	"all" // removes all verifications for this user (Example: don't do any verification on GabeN)
		// "1.1.1.1"	"vpn" // removes vpn method for this IP
		// "a"	"csgo_playtime" // removes the playtime check/requirement for every user that has the 'a' flag
		// "cd"	"vpn" // removes the vpn method for every user that has both 'c' and 'd' flags
		// "z"	"all" // removes all verifications for root users
		// "$FR"	"csgo_coin" // removes csgo_coin method for IPs located in France
		
		// START ADDING YOUR PLAYERS HERE
		
		"a"	"csgo_playtime"
	}
```
I would like all players who have **Prime Status in CSGO** to pass the verification even if they have a private profile and connect to the server.

I thought of putting it like this in the configuration:
```
"no_dupe_account"
{
	"Players" // Players whitelist
	{
		"a"	"csgo_playtime"
		""	"prime"
	}
```
Would it work in this case? 

What I mean is, player has never connected to the server, private profile, but he has **Prime Status**, so he can still connect to the servers.

**Comment by azalty** [comment]
Just set the prime status as a check and the player will be validated.
If you have any forced verification ('kick' mode, not 'check' mode), well sadly, you currently can't filter people that have the prime status to bypass forced verifications.

https://github.com/azalty/sm-no-dupe-account/wiki/FAQ#whats-a-check

Prime status -> set as a check
Other methods that require a public profile -> set as a check or disable

So yea, sadly this means that if you want people to have either the prime status or validate 2+ methods that requires a public profile, that's not possible currently.

**Comment by azalty** [comment]
If you really want prime people to be added as a possibility in the whitelist, you can ask! :)

**Comment by MatheusVRibeiro** [comment]
I would like to know this possibility, could you help me?

**Comment by azalty** [comment]
> I would like to know this possibility, could you help me?

What do you mean?

**Comment by crashzk** [comment]
> Just set the prime status as a check and the player will be validated. If you have any forced verification ('kick' mode, not 'check' mode), well sadly, you currently can't filter people that have the prime status to bypass forced verifications.
>

OK, I believe I got it, so if I configure it like this:
```
// (Requires SteamWorks)
// 0 = disabled
// 1 = is a user check that fails if user is not prime (will only work if user paid the game) + nda menu
// 2 = only add an !nda menu displaying non-prime players
// -
// Default: "1"
nda_prime "1"
```
Even if the player has a private steam profile, does it connect if it has prime status in CSGO? Would it be this?

> If you really want prime people to be added as a possibility in the whitelist, you can ask! :)
>
I believe that would be the case, the possibility of me whitelisting all players with Prime Status. If you have prime, enter the server even if you have a private profile.

If you don't have prime, it goes through the public profile verification.

Anyway, it wouldn't be something important, it was just something I thought about here.

**Comment by azalty** [comment]
@crashzk depends, what value are you using for "nda_playtime"?

**Comment by crashzk** [comment]
@azalty 
```
// (Requires SteamAPI Key)
// 0 = disabled
// any integer = is a user check that fails if he has less mins in playtime than asked or has private hours
// any negative integer = same as positive, but is not a check and will kick user
// -
// Default: "120"
nda_playtime "-7200"
```

**Comment by azalty** [comment]
> @azalty
> 
> ```
> // (Requires SteamAPI Key)
> // 0 = disabled
> // any integer = is a user check that fails if he has less mins in playtime than asked or has private hours
> // any negative integer = same as positive, but is not a check and will kick user
> // -
> // Default: "120"
> nda_playtime "-7200"
> ```

You currently cannot bypass 'forced methods' for players that have the prime status -> methods that are not a 'check' but kick players
You'll have to set it as a check
