### ISSUE TITLE
Function Kick NonPrime

### ISSUE THREAD

**Issue by crashzk** [azalty/sm-no-dupe-account#40]
I would like to know if it would be possible to make the user kicked if he does not have Prime Status in CSGO, even if he has passed in all others. In this case I am using the following settings.

File **`no_dupe_account.cfg`**:
```
// (Requires SteamWorks)
// 0 = disabled
// 1 = check for VPNs or proxies, and send an in-game alert to admins if someone is potentially using one (and a discord message if setup)
// 2 = is a user check that fails is user has a VPN
// 3 = kick user
// -
// Default: "1"
nda_vpn "0"

// 0 = disabled
// any integer = is a user check that fails if his level is under this value. Keep in mind if someone gets his service medal he will go back to level 1
// -
// Default: "2"
nda_level "0"

// (Requires SteamWorks)
// 0 = disabled
// 1 = is a user check that fails if user is not prime (will only work if user paid the game) + nda menu
// 2 = only add an !nda menu displaying non-prime players
// -
// Default: "1"
nda_prime "1"

// (Requires SteamAPI Key)
// 0 = disabled
// any integer = is a user check that fails if he has less mins in playtime than asked or has private hours
// any negative integer = same as positive, but is not a check and will kick user
// -
// Default: "120"
// 120 Horas = -7200 | 45 Horas = -2700
nda_playtime "-7200"

// (Requires SteamAPI Key)
// 0 = disabled
// any integer = is a user check that fails if his steam level is under this value or his profile is private
// any negative integer = same as positive, but is not a check and will kick user
// -
// Default: "5"
nda_steam_level "0"

// (Requires SteamAPI Key)
// 0 = disabled
// any integer = is a user check that fails if his steam account age is newer than this value in minutes or his profile is private
// any negative integer = same as positive, but is not a check and will kick user
// ~integer (ex: ~60) = same as negative, but will not kick user if his profile is private
// -
// Default: "1576800"
nda_steam_age "0"

// 0 = disabled
// 1 = is a user check that fails if he doesn't have any CS:GO coin/badge equipped
// 2 = kick user if he doesn't have any CS:GO coin/badge equipped (this is not recommended as a lot of players don't have a coin)
// -
// Default: "1"
nda_coin "0"

// (Requires SteamAPI Key)
// 0 = disabled
// any integer = kick player if he has been VAC banned at least X times
// -
// Default: "0"
nda_bans_vac "1"

// (Requires SteamAPI Key)
// 0 = disabled
// any integer = kick player if he has been Game banned at least X times
// -
// Default: "0"
nda_bans_game "1"

// (Requires SteamAPI Key)
// 0 = disabled
// 1 = kick player if he is community banned (spam, phishing, nudity...)
// These people will have private profiles and are unable to add friends or comment.
// 2 = send an in-game alert to admins if player is community banned (and a discord message if setup)
// -
// Default: "2"
nda_bans_community "2"

// (Requires SteamAPI Key)
// 0 = disabled
// any integer = kick player if he has been banned at least X times (VAC+Game bans)
// -
// Default: "0"
nda_bans_total "1"

// (Requires SteamAPI Key)
// 0 = disabled
// any positive integer = send an in-game alert to admins (and a discord message if setup) if player has been VAC or Game banned X days ago or less
// any negative integer = same as positive integer, but instead of sending an alert, it will kick the player
// -
// Default: "5"
// 5 Anos = -1825
nda_bans_recent "0"
```

File **`no_dupe_account.cfg`** I have the following immunity configured:
 ```
 "a"	"csgo_playtime;bans_game;prime"
 ```
 
That is, if the user has the flag **`a`**, he is a VIP and he is immune to **`csgo_playtime;bans_game;prime`**. Until then, everything is fine.
 
However, if the player is not a VIP, I would like that even if he has the necessary hours to play, if he does not have Prime Status, he will still be kicked.

**Comment by azalty** [comment]
Not currently possible. I didn't add this feature as there was a cvar that restricted non-prime players from joining the server, but since the whitelist system is here, I guess it makes sense to add this feature.

I'll add it soon, if I don't forget to. Feel free to ping me if I forget.

Please note that prime players that didn't buy the game but leveled up to lvl 21 while it was possible will still not be allowed!

**Comment by crashzk** [comment]
@azalty just so you don't forget. 😄

**Comment by azalty** [comment]
Feature added in [1.5.2 Beta 2](https://github.com/azalty/sm-no-dupe-account/tree/db08f592d98c358f108f94bb465bd9d55f639174) - located in the main branch

See [the wiki on Beta versions](https://github.com/azalty/sm-no-dupe-account/wiki/Beta-versions)

**Comment by crashzk** [comment]
First of all, thanks for this version. I'll be testing it and I'll get back to you with feedback.

A CSGO Prime Status question, using [prime.napas.cc](https://prime.napas.cc/) to check if a player is Prime or NomPrime, wouldn't it be better than checking in CSGO itself?

I ask because I don't know if this Prime Napas differs from Prime purchased or upgraded, as this feature used to be in CSGO.

**Comment by azalty** [comment]
> First of all, thanks for this version. I'll be testing it and I'll get back to you with feedback.
> 
> A CSGO Prime Status question, using [prime.napas.cc](https://prime.napas.cc/) to check if a player is Prime or NomPrime, wouldn't it be better than checking in CSGO itself?
> 
> I ask because I don't know if this Prime Napas differs from Prime purchased or upgraded, as this feature used to be in CSGO.

I don't think it'll be able to give better results than the current SteamWorks method.

Anyways, I only seem to get 'Forbidden' out of their API. There's no such thing as a 32bit int `accountid`. Their api seems really shitty, requiring an API key linked to a discord account for no reason, having a dick favicon, and a blurry documentation. Who knows what they log and what they do with our data.

**Comment by crashzk** [comment]
Just a feedback, so far it seems that everything is ok with this new function.

NomPrime players are being kicked, and if they are whitelisted they can get in. I'll be testing some more and come back with the final result.

**Comment by azalty** [comment]
Added in stable version [1.5.2](https://github.com/azalty/sm-no-dupe-account/releases/tag/1.5.2)
