### ISSUE TITLE
How the available checks work if the player leaves the profile private

### ISSUE THREAD

**Issue by crashzk** [azalty/sm-no-dupe-account#8]
If the player enters the Steam Profile server all public, but then he tries to connect again on the server but the Steam profile is all private, his connection would be refused since his profile is all private and the plugin is not able to make the checks?

**Comment by azalty** [comment]
Yes, this is the current behaviour (for profile dependant checks. Some aren't as cs:go level or VAC status or game ban status).

However a database system is planned to make the player able to join the server if he made public his profile.

**Comment by azalty** [comment]
If at least 1 check is passed, the player will be allowed. For example, if CSGO level 5 is a check, and Playtime 5h is another one, if "Player1" connects with a private profile and is level 8, he will be allowed, even if he didn't pass the playtime check.

If any method is set as mandatory (check each cvar description), the player will have to pass EACH of these mandatory methods and pass at least 1 check (if any check is configured)

Feel free to ask again if you didn't understand something

**Comment by crashzk** [comment]
I got it, thanks.

I think I will wait for this database system, anything I will contact you again.
